import type { QRContent } from './payloadParser';

export type PayloadEdgeCategory =
  | 'unicode'
  | 'escaped-delimiters'
  | 'duplicate-fields'
  | 'empty-fields'
  | 'control-characters'
  | 'large-payload'
  | 'standard';

export type PayloadFixture = {
  name: string;
  raw: string;
  expectedKind: QRContent['kind'];
  parserIds: string[];
  edgeCategories: PayloadEdgeCategory[];
  description: string;
};

const LARGE_TEXT = `QR large payload ${'A'.repeat(5000)} end`;

export const PAYLOAD_FIXTURE_CORPUS: PayloadFixture[] = [
  {
    name: 'url-simple',
    raw: 'https://example.com/some/path?q=1',
    expectedKind: 'url',
    parserIds: ['url'],
    edgeCategories: ['standard'],
    description: 'Canonical https URL with path and query.',
  },
  {
    name: 'url-unicode',
    raw: 'https://münchen.de/Grüße?q=café',
    expectedKind: 'url',
    parserIds: ['url'],
    edgeCategories: ['unicode'],
    description: 'Unicode host and path preserved without network lookup.',
  },
  {
    name: 'url-with-port',
    raw: 'https://example.com:8080/a?x=1#frag',
    expectedKind: 'url',
    parserIds: ['url'],
    edgeCategories: ['standard'],
    description: 'URL with port, query, and fragment.',
  },
  {
    name: 'url-control-fallback',
    raw: 'https://example.com/\x01bad',
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['control-characters'],
    description: 'Control character forces safe text fallback, original preserved.',
  },
  {
    name: 'text-plain',
    raw: 'Hello, this is plain text',
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['standard'],
    description: 'Ordinary prose falls back to text.',
  },
  {
    name: 'text-unicode-emoji',
    raw: 'Hello 🌍 日本語 café 🎉',
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['unicode'],
    description: 'Unicode and emoji preserved in text fallback.',
  },
  {
    name: 'text-control',
    raw: 'hello\x00world\x1F!',
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['control-characters'],
    description: 'Embedded controls sanitized in display, preserved in original.',
  },
  {
    name: 'text-large',
    raw: LARGE_TEXT,
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['large-payload'],
    description: 'Five-thousand-character payload never crashes; display truncates explicitly.',
  },
  {
    name: 'text-empty',
    raw: '',
    expectedKind: 'text',
    parserIds: [],
    edgeCategories: ['empty-fields'],
    description: 'Empty payload returns safe text result without throwing.',
  },
  {
    name: 'email-mailto',
    raw: 'mailto:alice@example.com?subject=Hello&body=World',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['standard'],
    description: 'mailto with subject and body.',
  },
  {
    name: 'email-matmsg',
    raw: 'MATMSG:TO:bob@example.com;SUB:Hi;BODY:How are you?;;',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['standard'],
    description: 'Legacy MATMSG email format.',
  },
  {
    name: 'email-matmsg-escaped',
    raw: 'MATMSG:TO:bob@example.com;SUB:Hi\\;there;BODY:Hello\\;world;;',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['escaped-delimiters'],
    description: 'MATMSG subject and body keep escaped semicolons.',
  },
  {
    name: 'email-matmsg-duplicate',
    raw: 'MATMSG:TO:first@example.com;TO:second@example.com;SUB:Hi;BODY:x;;',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['duplicate-fields'],
    description: 'Duplicate TO keeps the first value deterministically.',
  },
  {
    name: 'email-matmsg-empty-subject',
    raw: 'MATMSG:TO:bob@example.com;SUB:;BODY:Hello;;',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['empty-fields'],
    description: 'Empty subject field still parses as email.',
  },
  {
    name: 'email-unicode',
    raw: 'mailto:josé@münchen.de?subject=Grüße&body=café',
    expectedKind: 'email',
    parserIds: ['email'],
    edgeCategories: ['unicode'],
    description: 'Unicode local part, host, subject, and body.',
  },
  {
    name: 'phone-tel',
    raw: 'tel:+14155552671',
    expectedKind: 'phone',
    parserIds: ['phone'],
    edgeCategories: ['standard'],
    description: 'E.164 telephone URI.',
  },
  {
    name: 'phone-formatted',
    raw: 'tel:+1 (415) 555-2671',
    expectedKind: 'phone',
    parserIds: ['phone'],
    edgeCategories: ['standard'],
    description: 'Formatted number with spaces and punctuation.',
  },
  {
    name: 'sms-smsto',
    raw: 'SMSTO:+14155552671:Hello there',
    expectedKind: 'sms',
    parserIds: ['sms'],
    edgeCategories: ['standard'],
    description: 'SMSTO with number and message.',
  },
  {
    name: 'sms-with-body-param',
    raw: 'sms:+14155552671?body=Hello%20there',
    expectedKind: 'sms',
    parserIds: ['sms'],
    edgeCategories: ['standard'],
    description: 'sms: URI with encoded body parameter.',
  },
  {
    name: 'geo-simple',
    raw: 'geo:37.7749,-122.4194',
    expectedKind: 'geo',
    parserIds: ['geo'],
    edgeCategories: ['standard'],
    description: 'Bare latitude/longitude.',
  },
  {
    name: 'geo-with-query',
    raw: 'geo:48.8566,2.3522?q=Eiffel+Tower',
    expectedKind: 'geo',
    parserIds: ['geo'],
    edgeCategories: ['standard'],
    description: 'Coordinate with place query.',
  },
  {
    name: 'wifi-wpa',
    raw: 'WIFI:T:WPA;S:home;P:supersecret;;',
    expectedKind: 'wifi',
    parserIds: ['wifi'],
    edgeCategories: ['standard'],
    description: 'WPA network; password redacted from display.',
  },
  {
    name: 'wifi-open-empty-password',
    raw: 'WIFI:T:nopass;S:CoffeeShop;;',
    expectedKind: 'wifi',
    parserIds: ['wifi'],
    edgeCategories: ['empty-fields'],
    description: 'Open network omits password field entirely.',
  },
  {
    name: 'wifi-escaped',
    raw: 'WIFI:T:WPA;S:my\\;net\\:1;P:p\\;ss;;',
    expectedKind: 'wifi',
    parserIds: ['wifi'],
    edgeCategories: ['escaped-delimiters'],
    description: 'Escaped semicolons and colons inside SSID and password.',
  },
  {
    name: 'wifi-duplicate',
    raw: 'WIFI:T:WPA;S:first;S:second;P:x;;',
    expectedKind: 'wifi',
    parserIds: ['wifi'],
    edgeCategories: ['duplicate-fields'],
    description: 'Duplicate SSID keeps the first value.',
  },
  {
    name: 'contact-vcard',
    raw: 'BEGIN:VCARD\nVERSION:3.0\nFN:Jane Doe\nTEL:+14155552671\nEMAIL:jane@example.com\nEND:VCARD',
    expectedKind: 'contact',
    parserIds: ['contact'],
    edgeCategories: ['standard'],
    description: 'Minimal vCard with name, phone, and email.',
  },
  {
    name: 'contact-mecard-escaped',
    raw: 'MECARD:N:Doe\\;John;TEL:+14155552671;EMAIL:john@example.com;;',
    expectedKind: 'contact',
    parserIds: ['contact'],
    edgeCategories: ['escaped-delimiters'],
    description: 'MECARD with escaped semicolon in name.',
  },
  {
    name: 'contact-empty-fn',
    raw: 'BEGIN:VCARD\nVERSION:3.0\nFN:\nTEL:+14155552671\nEND:VCARD',
    expectedKind: 'contact',
    parserIds: ['contact'],
    edgeCategories: ['empty-fields'],
    description: 'Empty formatted name still yields a contact via phone.',
  },
  {
    name: 'contact-unicode',
    raw: 'BEGIN:VCARD\nVERSION:3.0\nFN:José Müller\nTEL:+14155552671\nEND:VCARD',
    expectedKind: 'contact',
    parserIds: ['contact'],
    edgeCategories: ['unicode'],
    description: 'Unicode display name in vCard.',
  },
  {
    name: 'calendar-vevent',
    raw: 'BEGIN:VEVENT\nSUMMARY:Team Meeting\nDTSTART:20260912T140000Z\nDTEND:20260912T150000Z\nLOCATION:Room 1\nEND:VEVENT',
    expectedKind: 'calendar',
    parserIds: ['calendar'],
    edgeCategories: ['standard'],
    description: 'Calendar event with title and times.',
  },
  {
    name: 'calendar-empty-location',
    raw: 'BEGIN:VEVENT\nSUMMARY:Standup\nDTSTART:20260912T140000Z\nLOCATION:\nEND:VEVENT',
    expectedKind: 'calendar',
    parserIds: ['calendar'],
    edgeCategories: ['empty-fields'],
    description: 'Empty location field tolerated.',
  },
  {
    name: 'otp-totp',
    raw: 'otpauth://totp/Example:alice@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Example',
    expectedKind: 'otp',
    parserIds: ['otp'],
    edgeCategories: ['standard'],
    description: 'TOTP enrollment; secret classified session-only.',
  },
  {
    name: 'custom-myapp',
    raw: 'myapp://pay?amount=10&to=bob',
    expectedKind: 'customScheme',
    parserIds: ['customScheme'],
    edgeCategories: ['standard'],
    description: 'Unknown app scheme stays identified with scheme shown.',
  },
  {
    name: 'custom-unicode',
    raw: 'myapp://greet?name=José',
    expectedKind: 'customScheme',
    parserIds: ['customScheme'],
    edgeCategories: ['unicode'],
    description: 'Unicode query inside custom scheme.',
  },
];
